import { STAGE_LABELS } from '../constants/options';

const HEADERS = {
  id: 'ID',
  activityName: 'Activity Name',
  location: 'Location',
  activityDate: 'Date of Activity',
  dealershipName: 'Dealership',
  customerName: 'Customer Name',
  contactNo: 'Contact No.',
  profile: 'Profile',
  segment: 'Segment',
  application: 'Application',
  currentVehicle: 'Current Vehicle',
  vehicleModelInterested: 'Model Interested',
  variant: 'Variant',
  exchangeInterested: 'Looking for Exchange',
  stage: 'Stage',
  creValidation: 'CRE Validation',
  creTag: 'CRE Tag',
  creRemarks: 'CRE Remarks',
  creTaggedAt: 'CRE Tagged At',
  smStatus: 'SM Status',
  smRemarks: 'SM Remarks',
  smTaggedAt: 'SM Tagged At',
  asmStatus: 'Final Status',
  asmRemarks: 'Final Remarks',
  asmTaggedAt: 'Final Tagged At',
  createdAt: 'Created At',
};

export function enquiryToCsvRow(e) {
  return {
    [HEADERS.id]: e.id,
    [HEADERS.activityName]: e.activityName,
    [HEADERS.location]: e.location,
    [HEADERS.activityDate]: e.activityDate,
    [HEADERS.dealershipName]: e.dealershipName,
    [HEADERS.customerName]: e.customerName,
    [HEADERS.contactNo]: e.contactNo,
    [HEADERS.profile]: e.profile,
    [HEADERS.segment]: e.segment,
    [HEADERS.application]: e.application || '',
    [HEADERS.currentVehicle]: e.currentVehicle || '',
    [HEADERS.vehicleModelInterested]: e.vehicleModelInterested,
    [HEADERS.variant]: e.variant || '',
    [HEADERS.exchangeInterested]: e.exchangeInterested ? 'Yes' : 'No',
    [HEADERS.stage]: STAGE_LABELS[e.stage] || e.stage,
    [HEADERS.creValidation]: e.cre?.validation || '',
    [HEADERS.creTag]: e.cre?.tag || '',
    [HEADERS.creRemarks]: e.cre?.remarks || '',
    [HEADERS.creTaggedAt]: e.cre?.taggedAt || '',
    [HEADERS.smStatus]: e.sm?.status || '',
    [HEADERS.smRemarks]: e.sm?.remarks || '',
    [HEADERS.smTaggedAt]: e.sm?.taggedAt || '',
    [HEADERS.asmStatus]: e.asm?.status || '',
    [HEADERS.asmRemarks]: e.asm?.remarks || '',
    [HEADERS.asmTaggedAt]: e.asm?.taggedAt || '',
    [HEADERS.createdAt]: e.createdAt,
  };
}
